name: mineral

services:
  miner1:
    image: sui/mineral-cli
    container_name: mineral-miner-1
    cpuset: "1"
    stop_grace_period: 1s
    restart: unless-stopped
    env_file: .env
    environment:
      WALLET: ${WALLET1}

  miner2:
    image: sui/mineral-cli
    container_name: mineral-miner-2
    cpuset: "2"
    stop_grace_period: 1s
    restart: unless-stopped
    env_file: .env
    environment:
      WALLET: ${WALLET2}

  miner3:
    image: sui/mineral-cli
    container_name: mineral-miner-3
    cpuset: "3"
    stop_grace_period: 1s
    restart: unless-stopped
    env_file: .env
    environment:
      WALLET: ${WALLET3}            